// Open Graph images (SEO-3, doc 13 section 4): 1200 by 630 PNGs rendered at build with sharp, the
// library Astro's image pipeline already runs on. An artifact with a cover or poster gets that
// image resized to the card; every other artifact gets a card drawn from its title, its collection,
// and the site name in the design tokens' colours. Nothing here is fetched or generated by a model.
import sharp from 'sharp';
import { dirname, join } from 'node:path';
import type { AnyEntry } from './catalog';

export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

// The light palette from src/styles/tokens.css (the card is a picture, so it carries its own colours;
// tests/contrast.spec.ts holds these equal to the tokens). F4 (D-32): the light palette C.
export const BG = '#ece4d8';
export const INK = '#221a11';
export const MUTED = '#574c3b';
export const ACCENT = '#8a4b1f';
const FONT = "Georgia, 'Times New Roman', serif";

const escapeXml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Greedy word wrap on an estimated glyph width; at most `max` lines, the last one shortened. */
export function wrapTitle(title: string, perLine: number, max: number): string[] {
  const words = title.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = '';
  for (const w of words) {
    if (line && (line + ' ' + w).length > perLine) {
      lines.push(line);
      line = w;
    } else line = line ? `${line} ${w}` : w;
  }
  if (line) lines.push(line);
  if (lines.length > max) {
    const kept = lines.slice(0, max);
    const last = kept[max - 1];
    kept[max - 1] = (last.includes(' ') ? last.replace(/\s+\S*$/, '') : last.slice(0, Math.max(1, perLine - 4))) + ' ...';
    return kept;
  }
  return lines;
}

/** The title card: kicker (collection and site), the title wrapped, an accent rule. */
export async function ogCard(opts: { title: string; kicker: string; site: string }): Promise<Buffer> {
  // 24 characters per line: at 64 px a fallback serif about a fifth wider than Georgia (the CI
  // runner has no Georgia) still fits the 1040 px of text width, so no line runs off the card.
  const lines = wrapTitle(opts.title, 24, 3);
  const size = lines.length > 2 ? 56 : 64;
  const lineHeight = size * 1.15;
  // The first baseline sits below the kicker (baseline 170) whatever the line count; three lines
  // at 56 px end near 400, well above the site name at 560.
  const top = 262;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${OG_WIDTH}" height="${OG_HEIGHT}" viewBox="0 0 ${OG_WIDTH} ${OG_HEIGHT}">
  <rect width="${OG_WIDTH}" height="${OG_HEIGHT}" fill="${BG}"/>
  <rect x="80" y="112" width="120" height="6" fill="${ACCENT}"/>
  <text x="80" y="170" font-family="${FONT}" font-size="26" letter-spacing="2" fill="${MUTED}">${escapeXml(opts.kicker.toUpperCase())}</text>
  ${lines.map((l, i) => `<text x="80" y="${Math.round(top + i * lineHeight)}" font-family="${FONT}" font-size="${size}" font-weight="700" fill="${INK}">${escapeXml(l)}</text>`).join('\n  ')}
  <text x="80" y="560" font-family="${FONT}" font-size="30" fill="${MUTED}">${escapeXml(opts.site)}</text>
</svg>`;
  return sharp(Buffer.from(svg)).png({ palette: true, compressionLevel: 9 }).toBuffer();
}

/** A cover or poster resized to the card, quantized so a photograph stays under the size rule. */
export async function ogFromCover(file: string): Promise<Buffer> {
  return sharp(file).resize(OG_WIDTH, OG_HEIGHT, { fit: 'cover', position: 'attention' }).png({ palette: true, quality: 80, compressionLevel: 9 }).toBuffer();
}

/** The artifact's cover or poster on disk, when it names one beside its Markdown file. */
export function coverFile(entry: AnyEntry): string | undefined {
  const data = entry.data as { cover?: string; poster?: string };
  const rel = data.cover ?? data.poster;
  if (!rel || rel.startsWith('/') || /^https?:/.test(rel)) return undefined;
  const filePath = (entry as unknown as { filePath?: string }).filePath;
  if (!filePath) return undefined;
  return join(process.cwd(), dirname(filePath), rel.replace(/^\.\//, ''));
}

/** The image's alt text for og:image:alt: the cover's own alt when the cover is the card. */
export function ogAlt(entry: AnyEntry, collectionLabel: string, siteName: string): string {
  const data = entry.data as { title: string; cover?: string; cover_alt?: string; poster?: string; poster_alt?: string };
  if (data.cover && data.cover_alt) return data.cover_alt;
  if (data.poster && data.poster_alt) return data.poster_alt;
  return `${data.title}, ${collectionLabel} on ${siteName}`;
}
